# Generated by Django 4.0.1 on 2022-01-19 08:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProductManager',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tg_id', models.PositiveIntegerField(verbose_name='Telegram id')),
                ('tg_username', models.CharField(blank=True, max_length=32, null=True, verbose_name='Ник в Telegram')),
                ('name', models.CharField(max_length=32, verbose_name='Имя')),
                ('surname', models.CharField(max_length=32, verbose_name='Фамилия')),
            ],
            options={
                'verbose_name': 'Продакт-менеджер',
                'verbose_name_plural': 'Продакт-менеджеры',
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256, verbose_name='Название проекта')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Краткое описание')),
                ('link_doc', models.URLField(blank=True, null=True, verbose_name='Ссылка на бриф')),
            ],
            options={
                'verbose_name': 'Типовой проект',
                'verbose_name_plural': 'Типовой проект',
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tg_id', models.PositiveIntegerField(verbose_name='Telegram id')),
                ('tg_username', models.CharField(blank=True, max_length=32, null=True, verbose_name='Ник в Telegram')),
                ('name', models.CharField(max_length=32, verbose_name='Имя')),
                ('surname', models.CharField(max_length=32, verbose_name='Фамилия')),
                ('level', models.CharField(choices=[('BG', 'Новичок'), ('BG+', 'Новичок+'), ('JR', 'Джуниор')], default='BG', max_length=3, verbose_name='Уровень ученика')),
            ],
            options={
                'verbose_name': 'Ученик',
                'verbose_name_plural': 'Ученики',
            },
        ),
        migrations.CreateModel(
            name='TeamProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_start', models.DateTimeField(verbose_name='Дата и время начала проекта')),
                ('date_end', models.DateTimeField(verbose_name='Дата и время окончания проекта')),
                ('discord_server_link', models.URLField(blank=True, null=True, verbose_name='Ссылка на discord сервер')),
                ('trello_desk_link', models.URLField(blank=True, null=True, verbose_name='Ссылка на trello доску')),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='bot.project')),
            ],
            options={
                'verbose_name': 'Проект команды',
                'verbose_name_plural': 'Проекты команд',
            },
        ),
        migrations.CreateModel(
            name='TimeSlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_slot', models.TimeField(verbose_name='Время начала созвона')),
                ('product_manager', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='bot.productmanager', verbose_name='Продакт-менеджер')),
                ('project_team', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='bot.teamproject', verbose_name='Проект команды')),
                ('student', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='bot.student', verbose_name='Ученик')),
            ],
            options={
                'verbose_name': 'Слот времени',
                'verbose_name_plural': 'Слоты времени',
            },
        ),
        migrations.AddField(
            model_name='productmanager',
            name='students',
            field=models.ManyToManyField(through='bot.TimeSlot', to='bot.Student'),
        ),
        migrations.AddConstraint(
            model_name='timeslot',
            constraint=models.UniqueConstraint(fields=('time_slot', 'product_manager', 'student', 'project_team'), name='Менеджер, студент, проект и слот времени'),
        ),
        migrations.AddConstraint(
            model_name='timeslot',
            constraint=models.UniqueConstraint(fields=('product_manager', 'student', 'project_team'), name='Менеджер, студент и проект'),
        ),
        migrations.AddConstraint(
            model_name='timeslot',
            constraint=models.UniqueConstraint(fields=('time_slot', 'student', 'project_team'), name='Слот времени, студент и проект'),
        ),
        migrations.AddConstraint(
            model_name='timeslot',
            constraint=models.UniqueConstraint(fields=('student', 'project_team'), name='Студент и проект команды'),
        ),
    ]
