# Generated by Django 4.0.1 on 2022-01-20 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bot", "0002_alter_productmanager_surname_alter_student_surname_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="productmanager",
            name="surname",
        ),
        migrations.RemoveField(
            model_name="student",
            name="surname",
        ),
        migrations.AddField(
            model_name="student",
            name="discord_username",
            field=models.CharField(
                blank=True, max_length=32, null=True, verbose_name="discord username"
            ),
        ),
        migrations.AddField(
            model_name="student",
            name="is_far_east",
            field=models.BooleanField(blank=True, null=True, verbose_name="Из ДВ?"),
        ),
        migrations.AlterField(
            model_name="productmanager",
            name="name",
            field=models.CharField(max_length=32, verbose_name="Имя и фамилия"),
        ),
        migrations.AlterField(
            model_name="productmanager",
            name="tg_id",
            field=models.PositiveIntegerField(
                blank=True, null=True, verbose_name="Telegram id"
            ),
        ),
        migrations.AlterField(
            model_name="productmanager",
            name="tg_username",
            field=models.CharField(
                default="cool_name", max_length=32, verbose_name="Ник в Telegram"
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="student",
            name="name",
            field=models.CharField(max_length=32, verbose_name="Имя и фамилия"),
        ),
        migrations.AlterField(
            model_name="student",
            name="tg_id",
            field=models.PositiveIntegerField(
                blank=True, null=True, verbose_name="Telegram id"
            ),
        ),
        migrations.AlterField(
            model_name="student",
            name="tg_username",
            field=models.CharField(
                default=123, max_length=32, verbose_name="Ник в Telegram"
            ),
            preserve_default=False,
        ),
    ]
