# Generated by Django 4.0.1 on 2022-01-21 08:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0004_timeslot_status'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='timeslot',
            name='Менеджер, студент, проект и слот времени',
        ),
        migrations.RemoveConstraint(
            model_name='timeslot',
            name='Менеджер, студент и проект',
        ),
        migrations.RemoveConstraint(
            model_name='timeslot',
            name='Слот времени, студент и проект',
        ),
        migrations.RemoveConstraint(
            model_name='timeslot',
            name='Студент и проект команды',
        ),
        migrations.RemoveField(
            model_name='timeslot',
            name='project_team',
        ),
        migrations.AddField(
            model_name='timeslot',
            name='team_project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='timeslots', to='bot.teamproject', verbose_name='Проект команды'),
        ),
        migrations.AlterField(
            model_name='teamproject',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='teamprojects', to='bot.project', verbose_name='Описание проекта'),
        ),
        migrations.AlterField(
            model_name='timeslot',
            name='product_manager',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='timeslots', to='bot.productmanager', verbose_name='Продакт-менеджер'),
        ),
        migrations.AlterField(
            model_name='timeslot',
            name='student',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='timeslots', to='bot.student', verbose_name='Ученик'),
        ),
        migrations.AddConstraint(
            model_name='timeslot',
            constraint=models.UniqueConstraint(fields=('time_slot', 'product_manager', 'student', 'team_project'), name='Менеджер, студент, проект и слот времени'),
        ),
        migrations.AddConstraint(
            model_name='timeslot',
            constraint=models.UniqueConstraint(fields=('product_manager', 'student', 'team_project'), name='Менеджер, студент и проект'),
        ),
        migrations.AddConstraint(
            model_name='timeslot',
            constraint=models.UniqueConstraint(fields=('time_slot', 'student', 'team_project'), name='Слот времени, студент и проект'),
        ),
        migrations.AddConstraint(
            model_name='timeslot',
            constraint=models.UniqueConstraint(fields=('student', 'team_project'), name='Студент и проект команды'),
        ),
    ]
