# Generated by Django 4.0.1 on 2022-01-22 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0005_remove_timeslot_менеджер, студент, проект и слот времени_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productmanager',
            name='tg_id',
            field=models.PositiveIntegerField(blank=True, null=True, unique=True, verbose_name='Telegram id'),
        ),
        migrations.AlterField(
            model_name='student',
            name='tg_id',
            field=models.PositiveIntegerField(blank=True, null=True, unique=True, verbose_name='Telegram id'),
        ),
        migrations.AlterField(
            model_name='timeslot',
            name='status',
            field=models.CharField(choices=[('BUSY', 'Есть запись на созвон'), ('FREE', 'Слот свободен'), ('NOAC', 'Не актуальное время, есть записись на другое время')], default='FREE', max_length=4, verbose_name='Статус'),
        ),
    ]
