# Generated by Django 4.0.1 on 2022-01-22 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0006_alter_productmanager_tg_id_alter_student_tg_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='is_far_east',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='Из ДВ?'),
        ),
    ]
