# Generated by Django 4.0.1 on 2022-01-24 04:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0007_alter_student_is_far_east'),
    ]

    operations = [
        migrations.CreateModel(
            name='PriorityStudents',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pairs_1', to='bot.student', verbose_name='Ученик 1')),
                ('student_2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pairs_2', to='bot.student', verbose_name='Ученик 2')),
            ],
            options={
                'verbose_name': 'Парный Студент',
                'verbose_name_plural': 'Парные Студенты',
            },
        ),
    ]
